In [1]:
import tensorflow as tf
import sys

In [2]:
print(f"wersja tensorflow: {tf.__version__}")
print(f"wersja pythona: {sys.version_info}")

wersja tensorflow: 2.19.0
wersja pythona: sys.version_info(major=3, minor=12, micro=11, releaselevel='final', serial=0)


In [3]:
#ładowanie danych mnist
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
#normalizacja danych
x_train,x_test = x_train/255.0,x_test/255.0

In [5]:
#prosty model sieci neuronowej
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)

])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
predictions = model(x_train[:1]).numpy()
print(predictions)

[[-0.26393074 -0.40606636  0.06205917  0.09138916 -0.21609572  0.34289306
   0.37955606  0.01685235  0.2156075  -0.38163847]]


In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.07521799, 0.06525189, 0.10420711, 0.10730878, 0.0789035 ,
        0.13799457, 0.14314775, 0.09960114, 0.12150177, 0.06686548]],
      dtype=float32)

In [8]:
#deklaracja propagacji wstecznej
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8656 - loss: 0.4643
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9549 - loss: 0.1503
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9660 - loss: 0.1109
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9727 - loss: 0.0868
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9764 - loss: 0.0717
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9805 - loss: 0.0648
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9823 - loss: 0.0522
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9838 - loss: 0.0508
Epoch 9/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9843 - loss: 0.0493
Epoch 10/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9856 - loss: 0.0436
Epoch 11/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9866 - loss: 0.0387
Epoch 12/20
1875/1875 ━━

In [11]:
#ocena modelu
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9794 - loss: 0.0879


[0.08788004517555237, 0.9793999791145325]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.3697594e-13, 4.4798505e-12, 9.7506378e-11, 8.9149733e-05,
        6.0263598e-18, 4.8592002e-11, 4.7425361e-19, 9.9991059e-01,
        3.2470599e-11, 2.7477014e-07],
       [3.6416772e-17, 7.4259287e-07, 9.9999928e-01, 2.9190619e-10,
        3.3096996e-36, 2.4776646e-13, 2.0869164e-13, 2.4618774e-22,
        1.3272212e-16, 1.3001857e-31],
       [8.2582785e-14, 9.9999058e-01, 4.6823466e-06, 4.2589137e-09,
        4.3368868e-09, 5.2484967e-08, 3.8802224e-07, 5.2563837e-07,
        3.7796149e-06, 6.1792286e-12],
       [9.9836761e-01, 3.3143280e-18, 1.6291018e-03, 2.3538247e-08,
        2.9023623e-13, 2.9746960e-08, 3.2955634e-06, 1.5673178e-09,
        9.9286557e-10, 9.7130846e-09],
       [1.0314291e-08, 5.4904100e-20, 6.5509465e-10, 1.0828241e-13,
        9.9987292e-01, 2.1484661e-11, 1.8447517e-09, 2.8448960e-07,
        1.2871308e-11, 1.2678246e-04]], dtype=float32)>

In [14]:
import numpy as np

In [15]:
w1 = probability_model(x_test[:1])
np.argmax(w1)

np.int64(7)

In [16]:
y_test[:1]

array([7], dtype=uint8)