In [1]:
import numpy as np
from sklearn.preprocessing import RobustScaler, StandardScaler

In [16]:
#przzygotowanie danych
X = np.array([
    [1.0,200.0],
    [2.0,300.0],
    [3.0,400.0],
    [4.0,500.0],
    [5.0,600.0],
    [1.5,1200.0],
    [45.0,2300.0]
])

In [17]:
scaler = StandardScaler()

In [18]:
x_scaled = scaler.fit_transform(X)

In [19]:
print(f"orygnialne dane:\n{X}")

orygnialne dane:
[[1.0e+00 2.0e+02]
 [2.0e+00 3.0e+02]
 [3.0e+00 4.0e+02]
 [4.0e+00 5.0e+02]
 [5.0e+00 6.0e+02]
 [1.5e+00 1.2e+03]
 [4.5e+01 2.3e+03]]


In [20]:
print(f"znormalizowane dane:\n{x_scaled}")

znormalizowane dane:
[[-0.52458438 -0.85195093]
 [-0.45720657 -0.70649589]
 [-0.38982876 -0.56104085]
 [-0.32245095 -0.41558582]
 [-0.25507314 -0.27013078]
 [-0.49089547  0.60259944]
 [ 2.44003927  2.20260483]]


In [7]:
rscaler = RobustScaler()

In [12]:
Xr = np.array([
    [1.e+00,2.e+02],
    [2.e+00,3.e+02],
    [3.e+00,4.e+02],
    [4.e+00,5.e+02],
    [5.e+00,6.e+02],
    [1.e+02,1.e+04],
    [2.4e+03,1.2e+04],
    [2.8e+05,2.2e+00]
])

In [13]:
xr_scaled = rscaler.fit_transform(Xr)

In [14]:
print(f"orygnialne dane:\n{Xr}")

orygnialne dane:
[[1.0e+00 2.0e+02]
 [2.0e+00 3.0e+02]
 [3.0e+00 4.0e+02]
 [4.0e+00 5.0e+02]
 [5.0e+00 6.0e+02]
 [1.0e+02 1.0e+04]
 [2.4e+03 1.2e+04]
 [2.8e+05 2.2e+00]]


In [15]:
print(f"znormalizowane dane:\n{xr_scaled}")

znormalizowane dane:
[[-5.20639643e-03 -9.34579439e-02]
 [-3.71885459e-03 -5.60747664e-02]
 [-2.23131276e-03 -1.86915888e-02]
 [-7.43770919e-04  1.86915888e-02]
 [ 7.43770919e-04  5.60747664e-02]
 [ 1.42060245e-01  3.57009346e+00]
 [ 3.56340647e+00  4.31775701e+00]
 [ 4.16505020e+02 -1.67401869e-01]]


In [21]:
scaler.inverse_transform(x_scaled)

array([[1.0e+00, 2.0e+02],
 [2.0e+00, 3.0e+02],
 [3.0e+00, 4.0e+02],
 [4.0e+00, 5.0e+02],
 [5.0e+00, 6.0e+02],
 [1.5e+00, 1.2e+03],
 [4.5e+01, 2.3e+03]])